spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/venus
    username: venus
    password: venus
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  mvc: # a fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher